version: "3.9"
services:
  app:
    image: productivity-app-backend
    container_name: productivity-app-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"